export const scheduleData = [
    {
        _id: 1,
        lessonNum: 3,
        class: { className: '10A' },
        subject: { subjectName: 'Toán', teacherName: 'Phan Đình Thế Trung' },
        status: true,
    },
    {
        _id: 2,
        lessonNum: 7,
        class: { className: '10A' },
        subject: { subjectName: 'Văn', teacherName: 'Trương Thiên Lộc' },
        status: false,
    },
    {
        _id: 3,
        lessonNum: 2,
        class: { className: '10B' },
        subject: { subjectName: 'Lịch sử', teacherName: 'Vũ Tiến Đạt' },
        status: true,
    },
    {
        _id: 4,
        lessonNum: 8,
        class: { className: '10B' },
        subject: { subjectName: 'Sinh học', teacherName: 'Lê Thanh Hải' },
        status: false,
    },
    {
        _id: 5,
        lessonNum: 4,
        class: { className: '10C' },
        subject: { subjectName: 'Địa lý', teacherName: 'Phạm Mạnh Tấn' },
        status: true,
    },
    {
        _id: 6,
        lessonNum: 6,
        class: { className: '10C' },
        subject: { subjectName: 'Toán', teacherName: 'Hồ Nhật Huy' },
        status: false,
    },
    {
        _id: 7,
        lessonNum: 5,
        class: { className: '10D' },
        subject: { subjectName: 'Văn', teacherName: 'Nguyễn Huy Hoàng' },
        status: true,
    },
    {
        _id: 8,
        lessonNum: 1,
        class: { className: '10D' },
        subject: { subjectName: 'Lịch sử', teacherName: 'Lê Nam Thành' },
        status: false,
    },
    {
        _id: 9,
        lessonNum: 9,
        class: { className: '10E' },
        subject: { subjectName: 'Sinh học', teacherName: 'Phan Thanh Dương' },
        status: true,
    },
    {
        _id: 10,
        lessonNum: 10,
        class: { className: '10E' },
        subject: { subjectName: 'Địa lý', teacherName: 'Trần Đình Khánh' },
        status: false,
    },
    {
        _id: 11,
        lessonNum: 3,
        class: { className: '10F' },
        subject: { subjectName: 'Toán', teacherName: 'Lương Quốc Toàn' },
        status: true,
    },
    {
        _id: 12,
        lessonNum: 7,
        class: { className: '10F' },
        subject: { subjectName: 'Văn', teacherName: 'Nguyễn Anh Tuấn Ngọc' },
        status: false,
    },
    {
        _id: 13,
        lessonNum: 5,
        class: { className: '10G' },
        subject: { subjectName: 'Lịch sử', teacherName: 'Nguyễn Văn Phong' },
        status: true,
    },
    {
        _id: 14,
        lessonNum: 8,
        class: { className: '10H' },
        subject: { subjectName: 'Sinh học', teacherName: 'admin' },
        status: false,
    },
    {
        _id: 15,
        lessonNum: 4,
        class: { className: '10I' },
        subject: { subjectName: 'Địa lý', teacherName: 'user1' },
        status: true,
    },
    {
        _id: 16,
        lessonNum: 2,
        class: { className: '10J' },
        subject: { subjectName: 'Toán', teacherName: 'user2' },
        status: false,
    },
    {
        _id: 17,
        lessonNum: 6,
        class: { className: '10K' },
        subject: { subjectName: 'Văn', teacherName: 'Huy' },
        status: true,
    },
]
export const teacherNames = [
    'Phan Đình Thế Trung',
    'Trương Thiên Lộc',
    'Vũ Tiến Đạt',
    'Lê Thanh Hải',
    'Phạm Mạnh Tấn',
    'Hồ Nhật Huy',
    'Nguyễn Huy Hoàng',
    'Lê Nam Thành',
    'Phan Thanh Dương',
    'Trần Đình Khánh',
    'Lương Quốc Toàn',
    'Nguyễn Anh Tuấn Ngọc',
    'Nguyễn Văn Phong',
]
